import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const INT_CODE='597055555532';
const INT_KEY='579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C';
const INT_API='https://webpay3gint.transbank.cl/rswebpaytransaction/api/webpay/v1.2/transactions';
const PROD_API='https://webpay3g.transbank.cl/rswebpaytransaction/api/webpay/v1.2/transactions';
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const isUuid=(v:unknown)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
function tbk(envValue?:string|null){const env=String(envValue||Deno.env.get('TBK_ENV')||'integration').toLowerCase();if(env==='production'){const commerceCode=String(Deno.env.get('TBK_COMMERCE_CODE')||'');const apiKey=String(Deno.env.get('TBK_API_KEY')||'');if(!commerceCode||!apiKey) throw new Error('Credenciales productivas de Transbank no configuradas.');return {commerceCode,apiKey,api:PROD_API};}return {commerceCode:INT_CODE,apiKey:INT_KEY,api:INT_API};}
Deno.serve(async(req)=>{
  if(req.method==='OPTIONS') return new Response('ok',{headers:cors});
  if(req.method!=='POST') return json({error:'Método no permitido.'},405);
  try{
    const url=Deno.env.get('SUPABASE_URL')||'';const anon=Deno.env.get('SUPABASE_ANON_KEY')||'';const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';const authorization=req.headers.get('Authorization')||'';
    const caller=createClient(url,anon,{global:{headers:{Authorization:authorization}},auth:{persistSession:false}});const auth=await caller.auth.getUser();const user=auth.data.user;if(!user) return json({error:'Sesión inválida.'},401);
    const body=await req.json().catch(()=>({})) as Record<string,unknown>;const txId=String(body.transaction_id||'').trim();const pagoId=String(body.pago_id||'').trim();if(!isUuid(txId)&&!isUuid(pagoId)) return json({error:'Transacción inválida.'},400);
    const admin=createClient(url,service,{auth:{persistSession:false}});let query=admin.from('transbank_transactions').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(1);query=isUuid(txId)?query.eq('id',txId):query.eq('pago_id',pagoId);const found=await query.maybeSingle();if(found.error||!found.data) return json({error:'Transacción no encontrada.'},404);const tx:any=found.data;
    if(tx.token_ws&&['INITIALIZED','COMMITTING','COMMIT_ERROR'].includes(String(tx.status||''))){try{const cfg=tbk(tx.environment);const response=await fetch(`${cfg.api}/${encodeURIComponent(tx.token_ws)}`,{method:'GET',headers:{'Content-Type':'application/json','Tbk-Api-Key-Id':cfg.commerceCode,'Tbk-Api-Key-Secret':cfg.apiKey}});if(response.ok){const data:any=await response.json().catch(()=>null);if(data){const authorized=Number(data.amount)===Number(tx.amount)&&String(data.buy_order||'')===String(tx.buy_order||'')&&Number(data.response_code)===0&&String(data.status||'').toUpperCase()==='AUTHORIZED';if(authorized){await admin.from('transbank_transactions').update({status:'APPROVED',response_code:Number(data.response_code),authorization_code:data.authorization_code||null,payment_type_code:data.payment_type_code||null,installments_number:Number.isFinite(Number(data.installments_number))?Number(data.installments_number):null,card_number:data.card_detail?.card_number||null,transaction_date:data.transaction_date||null,transbank_status:data.status||null,raw_response:{status:data},error_message:null,committed_at:tx.committed_at||new Date().toISOString()}).eq('id',tx.id);const p=await admin.from('pagos').select('monto,monto_cuota,estado').eq('id',tx.pago_id).maybeSingle();const cuota=Math.max(0,Number(p.data?.monto_cuota??p.data?.monto??0)||0);if(p.data&&!['pagado','paid'].includes(String(p.data.estado||'').toLowerCase())) await admin.from('pagos').update({estado:'pagado',monto_pagado:cuota,metodo_pago:'transbank',canal_recaudacion:'webpay_plus',paid_at:new Date().toISOString()}).eq('id',tx.pago_id);tx.status='APPROVED';tx.authorization_code=data.authorization_code||null;tx.transaction_date=data.transaction_date||null;tx.transbank_status=data.status||null;}else if(['FAILED','REVERSED','NULLIFIED'].includes(String(data.status||'').toUpperCase())){await admin.from('transbank_transactions').update({status:'REJECTED',transbank_status:data.status||null,response_code:Number.isFinite(Number(data.response_code))?Number(data.response_code):null,raw_response:{status:data}}).eq('id',tx.id);tx.status='REJECTED';}}}}catch(_){} }
    return json({ok:true,transaction:{id:tx.id,pago_id:tx.pago_id,status:tx.status,amount:Number(tx.amount),response_code:tx.response_code,authorization_code:tx.authorization_code,payment_type_code:tx.payment_type_code,installments_number:tx.installments_number,card_number:tx.card_number,transaction_date:tx.transaction_date,transbank_status:tx.transbank_status,environment:tx.environment,created_at:tx.created_at,committed_at:tx.committed_at,error_message:tx.error_message}});
  }catch(error){console.error('webpay-status',error);return json({error:(error as Error)?.message||'No se pudo consultar la transacción.'},500);}
});
